"""route_table_creation

Revision ID: 676358821b06
Revises: d73b52daaef1
Create Date: 2023-09-14 19:12:15.527552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676358821b06'
down_revision = 'd73b52daaef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=128), nullable=True),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('start', sa.String(length=64), nullable=True),
    sa.Column('destination', sa.String(length=64), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_route_name'), ['route_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_route_name'))

    op.drop_table('routes')
    # ### end Alembic commands ###
