"""Input table added

Revision ID: 737a1986923d
Revises: d784122619a7
Create Date: 2023-10-08 11:09:04.082671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737a1986923d'
down_revision = 'd784122619a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Age_Band_of_Driver', sa.Integer(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Time', sa.Boolean(), nullable=True),
    sa.Column('Speed_Limit', sa.Integer(), nullable=True),
    sa.Column('Light_Conditions', sa.String(length=64), nullable=True),
    sa.Column('Road_Surface_Conditions', sa.String(length=64), nullable=True),
    sa.Column('Junction_Control', sa.String(length=64), nullable=True),
    sa.Column('Sex_of_Driver', sa.String(length=1), nullable=True),
    sa.Column('Road_Type', sa.String(length=64), nullable=True),
    sa.Column('Weather_Conditions', sa.String(length=64), nullable=True),
    sa.Column('Urban_or_Rural_Area', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="date::date")
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Time(),
               existing_nullable=True,
               postgresql_using="time::time")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    op.drop_table('Input')
    # ### end Alembic commands ###
