"""Input table added V2.0

Revision ID: b7d4be2080ee
Revises: 737a1986923d
Create Date: 2023-11-04 17:44:42.752150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d4be2080ee'
down_revision = '737a1986923d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Input', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Probability_Fatal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Probability_Serious', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Probability_Slight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Combined_Probability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Input', schema=None) as batch_op:
        batch_op.drop_column('Combined_Probability')
        batch_op.drop_column('Probability_Slight')
        batch_op.drop_column('Probability_Serious')
        batch_op.drop_column('Probability_Fatal')

    # ### end Alembic commands ###
