"""Add drivers table

Revision ID: d73b52daaef1
Revises: 007872e19295
Create Date: 2023-09-13 20:11:24.049858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73b52daaef1'
down_revision = '007872e19295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('driver_age', sa.Integer(), nullable=True),
    sa.Column('driver_gender', sa.String(length=1), nullable=True),
    sa.Column('driver_address', sa.String(length=1024), nullable=True),
    sa.Column('driver_rating', sa.Float(), nullable=True),
    sa.Column('bus_driving_experience', sa.Float(), nullable=True),
    sa.Column('total_driving_experience', sa.Float(), nullable=True),
    sa.Column('no_of_major_accidents', sa.Integer(), nullable=True),
    sa.Column('no_of_minor_accidents', sa.Integer(), nullable=True),
    sa.Column('average_driving_hours_in_day_time', sa.Float(), nullable=True),
    sa.Column('average_driving_distance_in_day_time', sa.Float(), nullable=True),
    sa.Column('average_driving_hours_in_night_time', sa.Float(), nullable=True),
    sa.Column('average_driving_distance_in_night_time', sa.Float(), nullable=True),
    sa.Column('safety_training_completed', sa.Boolean(), nullable=True),
    sa.Column('prior_substance_use', sa.Boolean(), nullable=True),
    sa.Column('vision_status', sa.String(length=64), nullable=True),
    sa.Column('health_status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_driver_name'), ['driver_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_driver_name'))

    op.drop_table('drivers')
    # ### end Alembic commands ###
